/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */





declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  MiscSheetsDataCreateInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolsCreateOneWithoutMiscSheetsDataInput'] | null; // SchoolsCreateOneWithoutMiscSheetsDataInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  MiscSheetsDataCreateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'][] | null; // [MiscSheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MiscSheetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [MiscSheetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['MiscSheetsDataCreateWithoutSchoolsInput'][] | null; // [MiscSheetsDataCreateWithoutSchoolsInput!]
  }
  MiscSheetsDataCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['MiscSheetsDataCreateWithoutSchoolsInput']; // MiscSheetsDataCreateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetsDataWhereUniqueInput']; // MiscSheetsDataWhereUniqueInput!
  }
  MiscSheetsDataCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  MiscSheetsDataScalarWhereInput: { // input type
    AND?: NexusGenInputs['MiscSheetsDataScalarWhereInput'][] | null; // [MiscSheetsDataScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathDWG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPDF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPNG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathTIFF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['MiscSheetsDataScalarWhereInput'][] | null; // [MiscSheetsDataScalarWhereInput!]
    OR?: NexusGenInputs['MiscSheetsDataScalarWhereInput'][] | null; // [MiscSheetsDataScalarWhereInput!]
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    Sheet_Number?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  MiscSheetsDataUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolsUpdateOneWithoutMiscSheetsDataInput'] | null; // SchoolsUpdateOneWithoutMiscSheetsDataInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetsDataUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetsDataUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['MiscSheetsDataUpdateManyMutationInput']; // MiscSheetsDataUpdateManyMutationInput!
    where: NexusGenInputs['MiscSheetsDataScalarWhereInput']; // MiscSheetsDataScalarWhereInput!
  }
  MiscSheetsDataUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'][] | null; // [MiscSheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MiscSheetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [MiscSheetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['MiscSheetsDataCreateWithoutSchoolsInput'][] | null; // [MiscSheetsDataCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'][] | null; // [MiscSheetsDataWhereUniqueInput!]
    deleteMany?: NexusGenInputs['MiscSheetsDataScalarWhereInput'][] | null; // [MiscSheetsDataScalarWhereInput!]
    disconnect?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'][] | null; // [MiscSheetsDataWhereUniqueInput!]
    set?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'][] | null; // [MiscSheetsDataWhereUniqueInput!]
    update?: NexusGenInputs['MiscSheetsDataUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [MiscSheetsDataUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['MiscSheetsDataUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [MiscSheetsDataUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['MiscSheetsDataUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [MiscSheetsDataUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  MiscSheetsDataUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['MiscSheetsDataUpdateWithoutSchoolsInput']; // MiscSheetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetsDataWhereUniqueInput']; // MiscSheetsDataWhereUniqueInput!
  }
  MiscSheetsDataUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetsDataUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['MiscSheetsDataCreateWithoutSchoolsInput']; // MiscSheetsDataCreateWithoutSchoolsInput!
    update: NexusGenInputs['MiscSheetsDataUpdateWithoutSchoolsInput']; // MiscSheetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetsDataWhereUniqueInput']; // MiscSheetsDataWhereUniqueInput!
  }
  MiscSheetsDataWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  SchoolsCreateInput: { // input type
    Cluster?: NexusGenInputs['SchoolsCreateOneWithoutClusterSchoolsInput'] | null; // SchoolsCreateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsCreateManyWithoutClusterInput'] | null; // SchoolsCreateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataCreateManyWithoutSchoolsInput'] | null; // MiscSheetsDataCreateManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData?: NexusGenInputs['SetsDataCreateManyWithoutSchoolsInput'] | null; // SetsDataCreateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSchoolsInput'] | null; // SheetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsCreateManyWithoutClusterInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'][] | null; // [SchoolsWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutClusterInput'][] | null; // [SchoolsCreateOrConnectWithoutClusterInput!]
    create?: NexusGenInputs['SchoolsCreateWithoutClusterInput'][] | null; // [SchoolsCreateWithoutClusterInput!]
  }
  SchoolsCreateOneWithoutClusterSchoolsInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutClusterSchoolsInput'] | null; // SchoolsCreateOrConnectWithoutClusterSchoolsInput
    create?: NexusGenInputs['SchoolsCreateWithoutClusterSchoolsInput'] | null; // SchoolsCreateWithoutClusterSchoolsInput
  }
  SchoolsCreateOneWithoutMiscSheetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutMiscSheetsDataInput'] | null; // SchoolsCreateOrConnectWithoutMiscSheetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutMiscSheetsDataInput'] | null; // SchoolsCreateWithoutMiscSheetsDataInput
  }
  SchoolsCreateOneWithoutSetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutSetsDataInput'] | null; // SchoolsCreateOrConnectWithoutSetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutSetsDataInput'] | null; // SchoolsCreateWithoutSetsDataInput
  }
  SchoolsCreateOneWithoutSheetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutSheetsDataInput'] | null; // SchoolsCreateOrConnectWithoutSheetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutSheetsDataInput'] | null; // SchoolsCreateWithoutSheetsDataInput
  }
  SchoolsCreateOrConnectWithoutClusterInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutClusterInput']; // SchoolsCreateWithoutClusterInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsCreateOrConnectWithoutClusterSchoolsInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutClusterSchoolsInput']; // SchoolsCreateWithoutClusterSchoolsInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsCreateOrConnectWithoutMiscSheetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutMiscSheetsDataInput']; // SchoolsCreateWithoutMiscSheetsDataInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsCreateOrConnectWithoutSetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutSetsDataInput']; // SchoolsCreateWithoutSetsDataInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsCreateOrConnectWithoutSheetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutSheetsDataInput']; // SchoolsCreateWithoutSheetsDataInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsCreateWithoutClusterInput: { // input type
    ClusterSchools?: NexusGenInputs['SchoolsCreateManyWithoutClusterInput'] | null; // SchoolsCreateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataCreateManyWithoutSchoolsInput'] | null; // MiscSheetsDataCreateManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData?: NexusGenInputs['SetsDataCreateManyWithoutSchoolsInput'] | null; // SetsDataCreateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSchoolsInput'] | null; // SheetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsCreateWithoutClusterSchoolsInput: { // input type
    Cluster?: NexusGenInputs['SchoolsCreateOneWithoutClusterSchoolsInput'] | null; // SchoolsCreateOneWithoutClusterSchoolsInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataCreateManyWithoutSchoolsInput'] | null; // MiscSheetsDataCreateManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData?: NexusGenInputs['SetsDataCreateManyWithoutSchoolsInput'] | null; // SetsDataCreateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSchoolsInput'] | null; // SheetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsCreateWithoutMiscSheetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsCreateOneWithoutClusterSchoolsInput'] | null; // SchoolsCreateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsCreateManyWithoutClusterInput'] | null; // SchoolsCreateManyWithoutClusterInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData?: NexusGenInputs['SetsDataCreateManyWithoutSchoolsInput'] | null; // SetsDataCreateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSchoolsInput'] | null; // SheetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsCreateWithoutSetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsCreateOneWithoutClusterSchoolsInput'] | null; // SchoolsCreateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsCreateManyWithoutClusterInput'] | null; // SchoolsCreateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataCreateManyWithoutSchoolsInput'] | null; // MiscSheetsDataCreateManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSchoolsInput'] | null; // SheetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsCreateWithoutSheetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsCreateOneWithoutClusterSchoolsInput'] | null; // SchoolsCreateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsCreateManyWithoutClusterInput'] | null; // SchoolsCreateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataCreateManyWithoutSchoolsInput'] | null; // MiscSheetsDataCreateManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData?: NexusGenInputs['SetsDataCreateManyWithoutSchoolsInput'] | null; // SetsDataCreateManyWithoutSchoolsInput
  }
  SchoolsScalarWhereInput: { // input type
    AND?: NexusGenInputs['SchoolsScalarWhereInput'][] | null; // [SchoolsScalarWhereInput!]
    ClusterID?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['SchoolsScalarWhereInput'][] | null; // [SchoolsScalarWhereInput!]
    OR?: NexusGenInputs['SchoolsScalarWhereInput'][] | null; // [SchoolsScalarWhereInput!]
    SchoolID?: NexusGenInputs['StringFilter'] | null; // StringFilter
    SchoolName?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  SchoolsUpdateInput: { // input type
    Cluster?: NexusGenInputs['SchoolsUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolsUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsUpdateManyWithoutClusterInput'] | null; // SchoolsUpdateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataUpdateManyWithoutSchoolsInput'] | null; // MiscSheetsDataUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateManyWithoutSchoolsInput'] | null; // SetsDataUpdateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSchoolsInput'] | null; // SheetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpdateManyMutationInput: { // input type
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  SchoolsUpdateManyWithWhereWithoutClusterInput: { // input type
    data: NexusGenInputs['SchoolsUpdateManyMutationInput']; // SchoolsUpdateManyMutationInput!
    where: NexusGenInputs['SchoolsScalarWhereInput']; // SchoolsScalarWhereInput!
  }
  SchoolsUpdateManyWithoutClusterInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'][] | null; // [SchoolsWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutClusterInput'][] | null; // [SchoolsCreateOrConnectWithoutClusterInput!]
    create?: NexusGenInputs['SchoolsCreateWithoutClusterInput'][] | null; // [SchoolsCreateWithoutClusterInput!]
    delete?: NexusGenInputs['SchoolsWhereUniqueInput'][] | null; // [SchoolsWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SchoolsScalarWhereInput'][] | null; // [SchoolsScalarWhereInput!]
    disconnect?: NexusGenInputs['SchoolsWhereUniqueInput'][] | null; // [SchoolsWhereUniqueInput!]
    set?: NexusGenInputs['SchoolsWhereUniqueInput'][] | null; // [SchoolsWhereUniqueInput!]
    update?: NexusGenInputs['SchoolsUpdateWithWhereUniqueWithoutClusterInput'][] | null; // [SchoolsUpdateWithWhereUniqueWithoutClusterInput!]
    updateMany?: NexusGenInputs['SchoolsUpdateManyWithWhereWithoutClusterInput'][] | null; // [SchoolsUpdateManyWithWhereWithoutClusterInput!]
    upsert?: NexusGenInputs['SchoolsUpsertWithWhereUniqueWithoutClusterInput'][] | null; // [SchoolsUpsertWithWhereUniqueWithoutClusterInput!]
  }
  SchoolsUpdateOneWithoutClusterSchoolsInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutClusterSchoolsInput'] | null; // SchoolsCreateOrConnectWithoutClusterSchoolsInput
    create?: NexusGenInputs['SchoolsCreateWithoutClusterSchoolsInput'] | null; // SchoolsCreateWithoutClusterSchoolsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolsUpdateWithoutClusterSchoolsInput'] | null; // SchoolsUpdateWithoutClusterSchoolsInput
    upsert?: NexusGenInputs['SchoolsUpsertWithoutClusterSchoolsInput'] | null; // SchoolsUpsertWithoutClusterSchoolsInput
  }
  SchoolsUpdateOneWithoutMiscSheetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutMiscSheetsDataInput'] | null; // SchoolsCreateOrConnectWithoutMiscSheetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutMiscSheetsDataInput'] | null; // SchoolsCreateWithoutMiscSheetsDataInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolsUpdateWithoutMiscSheetsDataInput'] | null; // SchoolsUpdateWithoutMiscSheetsDataInput
    upsert?: NexusGenInputs['SchoolsUpsertWithoutMiscSheetsDataInput'] | null; // SchoolsUpsertWithoutMiscSheetsDataInput
  }
  SchoolsUpdateOneWithoutSetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutSetsDataInput'] | null; // SchoolsCreateOrConnectWithoutSetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutSetsDataInput'] | null; // SchoolsCreateWithoutSetsDataInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolsUpdateWithoutSetsDataInput'] | null; // SchoolsUpdateWithoutSetsDataInput
    upsert?: NexusGenInputs['SchoolsUpsertWithoutSetsDataInput'] | null; // SchoolsUpsertWithoutSetsDataInput
  }
  SchoolsUpdateOneWithoutSheetsDataInput: { // input type
    connect?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolsCreateOrConnectWithoutSheetsDataInput'] | null; // SchoolsCreateOrConnectWithoutSheetsDataInput
    create?: NexusGenInputs['SchoolsCreateWithoutSheetsDataInput'] | null; // SchoolsCreateWithoutSheetsDataInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolsUpdateWithoutSheetsDataInput'] | null; // SchoolsUpdateWithoutSheetsDataInput
    upsert?: NexusGenInputs['SchoolsUpsertWithoutSheetsDataInput'] | null; // SchoolsUpsertWithoutSheetsDataInput
  }
  SchoolsUpdateWithWhereUniqueWithoutClusterInput: { // input type
    data: NexusGenInputs['SchoolsUpdateWithoutClusterInput']; // SchoolsUpdateWithoutClusterInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsUpdateWithoutClusterInput: { // input type
    ClusterSchools?: NexusGenInputs['SchoolsUpdateManyWithoutClusterInput'] | null; // SchoolsUpdateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataUpdateManyWithoutSchoolsInput'] | null; // MiscSheetsDataUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateManyWithoutSchoolsInput'] | null; // SetsDataUpdateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSchoolsInput'] | null; // SheetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpdateWithoutClusterSchoolsInput: { // input type
    Cluster?: NexusGenInputs['SchoolsUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolsUpdateOneWithoutClusterSchoolsInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataUpdateManyWithoutSchoolsInput'] | null; // MiscSheetsDataUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateManyWithoutSchoolsInput'] | null; // SetsDataUpdateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSchoolsInput'] | null; // SheetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpdateWithoutMiscSheetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolsUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsUpdateManyWithoutClusterInput'] | null; // SchoolsUpdateManyWithoutClusterInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateManyWithoutSchoolsInput'] | null; // SetsDataUpdateManyWithoutSchoolsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSchoolsInput'] | null; // SheetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpdateWithoutSetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolsUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsUpdateManyWithoutClusterInput'] | null; // SchoolsUpdateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataUpdateManyWithoutSchoolsInput'] | null; // MiscSheetsDataUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSchoolsInput'] | null; // SheetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpdateWithoutSheetsDataInput: { // input type
    Cluster?: NexusGenInputs['SchoolsUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolsUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolsUpdateManyWithoutClusterInput'] | null; // SchoolsUpdateManyWithoutClusterInput
    MiscSheetsData?: NexusGenInputs['MiscSheetsDataUpdateManyWithoutSchoolsInput'] | null; // MiscSheetsDataUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateManyWithoutSchoolsInput'] | null; // SetsDataUpdateManyWithoutSchoolsInput
  }
  SchoolsUpsertWithWhereUniqueWithoutClusterInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutClusterInput']; // SchoolsCreateWithoutClusterInput!
    update: NexusGenInputs['SchoolsUpdateWithoutClusterInput']; // SchoolsUpdateWithoutClusterInput!
    where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
  }
  SchoolsUpsertWithoutClusterSchoolsInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutClusterSchoolsInput']; // SchoolsCreateWithoutClusterSchoolsInput!
    update: NexusGenInputs['SchoolsUpdateWithoutClusterSchoolsInput']; // SchoolsUpdateWithoutClusterSchoolsInput!
  }
  SchoolsUpsertWithoutMiscSheetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutMiscSheetsDataInput']; // SchoolsCreateWithoutMiscSheetsDataInput!
    update: NexusGenInputs['SchoolsUpdateWithoutMiscSheetsDataInput']; // SchoolsUpdateWithoutMiscSheetsDataInput!
  }
  SchoolsUpsertWithoutSetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutSetsDataInput']; // SchoolsCreateWithoutSetsDataInput!
    update: NexusGenInputs['SchoolsUpdateWithoutSetsDataInput']; // SchoolsUpdateWithoutSetsDataInput!
  }
  SchoolsUpsertWithoutSheetsDataInput: { // input type
    create: NexusGenInputs['SchoolsCreateWithoutSheetsDataInput']; // SchoolsCreateWithoutSheetsDataInput!
    update: NexusGenInputs['SchoolsUpdateWithoutSheetsDataInput']; // SchoolsUpdateWithoutSheetsDataInput!
  }
  SchoolsWhereUniqueInput: { // input type
    id?: number | null; // Int
    SchoolID?: string | null; // String
  }
  SetsDataCreateInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolsCreateOneWithoutSetsDataInput'] | null; // SchoolsCreateOneWithoutSetsDataInput
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSetsDataInput'] | null; // SheetsDataCreateManyWithoutSetsDataInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetsDataCreateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SetsDataWhereUniqueInput'][] | null; // [SetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [SetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SetsDataCreateWithoutSchoolsInput'][] | null; // [SetsDataCreateWithoutSchoolsInput!]
  }
  SetsDataCreateOneWithoutSheetsDataInput: { // input type
    connect?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SetsDataCreateOrConnectWithoutSheetsDataInput'] | null; // SetsDataCreateOrConnectWithoutSheetsDataInput
    create?: NexusGenInputs['SetsDataCreateWithoutSheetsDataInput'] | null; // SetsDataCreateWithoutSheetsDataInput
  }
  SetsDataCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SetsDataCreateWithoutSchoolsInput']; // SetsDataCreateWithoutSchoolsInput!
    where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
  }
  SetsDataCreateOrConnectWithoutSheetsDataInput: { // input type
    create: NexusGenInputs['SetsDataCreateWithoutSheetsDataInput']; // SetsDataCreateWithoutSheetsDataInput!
    where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
  }
  SetsDataCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    SheetsData?: NexusGenInputs['SheetsDataCreateManyWithoutSetsDataInput'] | null; // SheetsDataCreateManyWithoutSetsDataInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetsDataCreateWithoutSheetsDataInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolsCreateOneWithoutSetsDataInput'] | null; // SchoolsCreateOneWithoutSetsDataInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetsDataScalarWhereInput: { // input type
    AND?: NexusGenInputs['SetsDataScalarWhereInput'][] | null; // [SetsDataScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    ID?: NexusGenInputs['StringFilter'] | null; // StringFilter
    Key?: NexusGenInputs['IntFilter'] | null; // IntFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['SetsDataScalarWhereInput'][] | null; // [SetsDataScalarWhereInput!]
    OR?: NexusGenInputs['SetsDataScalarWhereInput'][] | null; // [SetsDataScalarWhereInput!]
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Type?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  SetsDataUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolsUpdateOneWithoutSetsDataInput'] | null; // SchoolsUpdateOneWithoutSetsDataInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSetsDataInput'] | null; // SheetsDataUpdateManyWithoutSetsDataInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetsDataUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetsDataUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SetsDataUpdateManyMutationInput']; // SetsDataUpdateManyMutationInput!
    where: NexusGenInputs['SetsDataScalarWhereInput']; // SetsDataScalarWhereInput!
  }
  SetsDataUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SetsDataWhereUniqueInput'][] | null; // [SetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [SetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SetsDataCreateWithoutSchoolsInput'][] | null; // [SetsDataCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['SetsDataWhereUniqueInput'][] | null; // [SetsDataWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SetsDataScalarWhereInput'][] | null; // [SetsDataScalarWhereInput!]
    disconnect?: NexusGenInputs['SetsDataWhereUniqueInput'][] | null; // [SetsDataWhereUniqueInput!]
    set?: NexusGenInputs['SetsDataWhereUniqueInput'][] | null; // [SetsDataWhereUniqueInput!]
    update?: NexusGenInputs['SetsDataUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [SetsDataUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['SetsDataUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [SetsDataUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['SetsDataUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [SetsDataUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  SetsDataUpdateOneWithoutSheetsDataInput: { // input type
    connect?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SetsDataCreateOrConnectWithoutSheetsDataInput'] | null; // SetsDataCreateOrConnectWithoutSheetsDataInput
    create?: NexusGenInputs['SetsDataCreateWithoutSheetsDataInput'] | null; // SetsDataCreateWithoutSheetsDataInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SetsDataUpdateWithoutSheetsDataInput'] | null; // SetsDataUpdateWithoutSheetsDataInput
    upsert?: NexusGenInputs['SetsDataUpsertWithoutSheetsDataInput'] | null; // SetsDataUpsertWithoutSheetsDataInput
  }
  SetsDataUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SetsDataUpdateWithoutSchoolsInput']; // SetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
  }
  SetsDataUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SheetsData?: NexusGenInputs['SheetsDataUpdateManyWithoutSetsDataInput'] | null; // SheetsDataUpdateManyWithoutSetsDataInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetsDataUpdateWithoutSheetsDataInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolsUpdateOneWithoutSetsDataInput'] | null; // SchoolsUpdateOneWithoutSetsDataInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetsDataUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SetsDataCreateWithoutSchoolsInput']; // SetsDataCreateWithoutSchoolsInput!
    update: NexusGenInputs['SetsDataUpdateWithoutSchoolsInput']; // SetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
  }
  SetsDataUpsertWithoutSheetsDataInput: { // input type
    create: NexusGenInputs['SetsDataCreateWithoutSheetsDataInput']; // SetsDataCreateWithoutSheetsDataInput!
    update: NexusGenInputs['SetsDataUpdateWithoutSheetsDataInput']; // SetsDataUpdateWithoutSheetsDataInput!
  }
  SetsDataWhereUniqueInput: { // input type
    Key?: number | null; // Int
  }
  SheetsDataCreateInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolsCreateOneWithoutSheetsDataInput'] | null; // SchoolsCreateOneWithoutSheetsDataInput
    SetID?: string | null; // String
    SetsData?: NexusGenInputs['SetsDataCreateOneWithoutSheetsDataInput'] | null; // SetsDataCreateOneWithoutSheetsDataInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetsDataCreateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [SheetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SheetsDataCreateWithoutSchoolsInput'][] | null; // [SheetsDataCreateWithoutSchoolsInput!]
  }
  SheetsDataCreateManyWithoutSetsDataInput: { // input type
    connect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetsDataCreateOrConnectWithoutSetsDataInput'][] | null; // [SheetsDataCreateOrConnectWithoutSetsDataInput!]
    create?: NexusGenInputs['SheetsDataCreateWithoutSetsDataInput'][] | null; // [SheetsDataCreateWithoutSetsDataInput!]
  }
  SheetsDataCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SheetsDataCreateWithoutSchoolsInput']; // SheetsDataCreateWithoutSchoolsInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataCreateOrConnectWithoutSetsDataInput: { // input type
    create: NexusGenInputs['SheetsDataCreateWithoutSetsDataInput']; // SheetsDataCreateWithoutSetsDataInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    SetID?: string | null; // String
    SetsData?: NexusGenInputs['SetsDataCreateOneWithoutSheetsDataInput'] | null; // SetsDataCreateOneWithoutSheetsDataInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetsDataCreateWithoutSetsDataInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolsCreateOneWithoutSheetsDataInput'] | null; // SchoolsCreateOneWithoutSheetsDataInput
    SetID?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetsDataScalarWhereInput: { // input type
    AND?: NexusGenInputs['SheetsDataScalarWhereInput'][] | null; // [SheetsDataScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathDWG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPDF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPNG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathTIFF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['SheetsDataScalarWhereInput'][] | null; // [SheetsDataScalarWhereInput!]
    OR?: NexusGenInputs['SheetsDataScalarWhereInput'][] | null; // [SheetsDataScalarWhereInput!]
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    set_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    SetID?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Sheet_Number?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  SheetsDataUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolsUpdateOneWithoutSheetsDataInput'] | null; // SchoolsUpdateOneWithoutSheetsDataInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateOneWithoutSheetsDataInput'] | null; // SetsDataUpdateOneWithoutSheetsDataInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetsDataUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetsDataUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SheetsDataUpdateManyMutationInput']; // SheetsDataUpdateManyMutationInput!
    where: NexusGenInputs['SheetsDataScalarWhereInput']; // SheetsDataScalarWhereInput!
  }
  SheetsDataUpdateManyWithWhereWithoutSetsDataInput: { // input type
    data: NexusGenInputs['SheetsDataUpdateManyMutationInput']; // SheetsDataUpdateManyMutationInput!
    where: NexusGenInputs['SheetsDataScalarWhereInput']; // SheetsDataScalarWhereInput!
  }
  SheetsDataUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetsDataCreateOrConnectWithoutSchoolsInput'][] | null; // [SheetsDataCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SheetsDataCreateWithoutSchoolsInput'][] | null; // [SheetsDataCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SheetsDataScalarWhereInput'][] | null; // [SheetsDataScalarWhereInput!]
    disconnect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    set?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    update?: NexusGenInputs['SheetsDataUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [SheetsDataUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['SheetsDataUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [SheetsDataUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['SheetsDataUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [SheetsDataUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  SheetsDataUpdateManyWithoutSetsDataInput: { // input type
    connect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetsDataCreateOrConnectWithoutSetsDataInput'][] | null; // [SheetsDataCreateOrConnectWithoutSetsDataInput!]
    create?: NexusGenInputs['SheetsDataCreateWithoutSetsDataInput'][] | null; // [SheetsDataCreateWithoutSetsDataInput!]
    delete?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SheetsDataScalarWhereInput'][] | null; // [SheetsDataScalarWhereInput!]
    disconnect?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    set?: NexusGenInputs['SheetsDataWhereUniqueInput'][] | null; // [SheetsDataWhereUniqueInput!]
    update?: NexusGenInputs['SheetsDataUpdateWithWhereUniqueWithoutSetsDataInput'][] | null; // [SheetsDataUpdateWithWhereUniqueWithoutSetsDataInput!]
    updateMany?: NexusGenInputs['SheetsDataUpdateManyWithWhereWithoutSetsDataInput'][] | null; // [SheetsDataUpdateManyWithWhereWithoutSetsDataInput!]
    upsert?: NexusGenInputs['SheetsDataUpsertWithWhereUniqueWithoutSetsDataInput'][] | null; // [SheetsDataUpsertWithWhereUniqueWithoutSetsDataInput!]
  }
  SheetsDataUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SheetsDataUpdateWithoutSchoolsInput']; // SheetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataUpdateWithWhereUniqueWithoutSetsDataInput: { // input type
    data: NexusGenInputs['SheetsDataUpdateWithoutSetsDataInput']; // SheetsDataUpdateWithoutSetsDataInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetsData?: NexusGenInputs['SetsDataUpdateOneWithoutSheetsDataInput'] | null; // SetsDataUpdateOneWithoutSheetsDataInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetsDataUpdateWithoutSetsDataInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolsUpdateOneWithoutSheetsDataInput'] | null; // SchoolsUpdateOneWithoutSheetsDataInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetsDataUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SheetsDataCreateWithoutSchoolsInput']; // SheetsDataCreateWithoutSchoolsInput!
    update: NexusGenInputs['SheetsDataUpdateWithoutSchoolsInput']; // SheetsDataUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataUpsertWithWhereUniqueWithoutSetsDataInput: { // input type
    create: NexusGenInputs['SheetsDataCreateWithoutSetsDataInput']; // SheetsDataCreateWithoutSetsDataInput!
    update: NexusGenInputs['SheetsDataUpdateWithoutSetsDataInput']; // SheetsDataUpdateWithoutSetsDataInput!
    where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
  }
  SheetsDataWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserUpdateInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    isAdmin?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    username?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // String
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  MiscSheetsData: { // root type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    id: number; // Int!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    school_id?: number | null; // Int
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Schools: { // root type
    ClusterID?: string | null; // String
    id: number; // Int!
    SchoolID: string; // String!
    SchoolName: string; // String!
  }
  SetsData: { // root type
    Day?: string | null; // String
    ID: string; // String!
    Key: number; // Int!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    school_id?: number | null; // Int
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SheetsData: { // root type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    id: number; // Int!
    Month?: string | null; // String
    school_id?: number | null; // Int
    set_id?: number | null; // Int
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  User: { // root type
    id: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  MiscSheetsData: { // field return type
    Day: string | null; // String
    FilePathDWG: string | null; // String
    FilePathPDF: string | null; // String
    FilePathPNG: string | null; // String
    FilePathTIFF: string | null; // String
    id: number; // Int!
    LocationNumber: string | null; // String
    Month: string | null; // String
    school_id: number | null; // Int
    Schools: NexusGenRootTypes['Schools'] | null; // Schools
    Sheet_Number: string | null; // String
    Title: string | null; // String
    Year: string | null; // String
  }
  Mutation: { // field return type
    createOneMiscSheetsData: NexusGenRootTypes['MiscSheetsData']; // MiscSheetsData!
    createOneSchools: NexusGenRootTypes['Schools']; // Schools!
    createOneSetsData: NexusGenRootTypes['SetsData']; // SetsData!
    createOneSheetsData: NexusGenRootTypes['SheetsData']; // SheetsData!
    createSchool: NexusGenRootTypes['Schools']; // Schools!
    deleteOneMiscSheetsData: NexusGenRootTypes['MiscSheetsData'] | null; // MiscSheetsData
    deleteOneSchools: NexusGenRootTypes['Schools'] | null; // Schools
    deleteOneSetsData: NexusGenRootTypes['SetsData'] | null; // SetsData
    deleteOneSheetsData: NexusGenRootTypes['SheetsData'] | null; // SheetsData
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
    deleteSchool: NexusGenRootTypes['Schools']; // Schools!
    login: NexusGenRootTypes['User'] | null; // User
    logout: NexusGenRootTypes['User'] | null; // User
    register: NexusGenRootTypes['User'] | null; // User
    updateOneMiscSheetsData: NexusGenRootTypes['MiscSheetsData'] | null; // MiscSheetsData
    updateOneSchools: NexusGenRootTypes['Schools'] | null; // Schools
    updateOneSetsData: NexusGenRootTypes['SetsData'] | null; // SetsData
    updateOneSheetsData: NexusGenRootTypes['SheetsData'] | null; // SheetsData
    updateOneUser: NexusGenRootTypes['User'] | null; // User
    updateSchool: NexusGenRootTypes['Schools']; // Schools!
  }
  Query: { // field return type
    allClusters: Array<NexusGenRootTypes['Schools'] | null>; // [Schools]!
    allSchools: Array<NexusGenRootTypes['Schools'] | null>; // [Schools]!
    allUsers: Array<NexusGenRootTypes['User'] | null>; // [User]!
    miscSheetsData: NexusGenRootTypes['MiscSheetsData'][]; // [MiscSheetsData!]!
    schools: NexusGenRootTypes['Schools'][]; // [Schools!]!
    setsData: NexusGenRootTypes['SetsData'][]; // [SetsData!]!
    sheetsData: NexusGenRootTypes['SheetsData'][]; // [SheetsData!]!
  }
  Schools: { // field return type
    Cluster: NexusGenRootTypes['Schools'] | null; // Schools
    ClusterID: string | null; // String
    ClusterSchools: NexusGenRootTypes['Schools'][]; // [Schools!]!
    id: number; // Int!
    MiscSheetsData: NexusGenRootTypes['MiscSheetsData'][]; // [MiscSheetsData!]!
    SchoolID: string; // String!
    SchoolName: string; // String!
    SetsData: NexusGenRootTypes['SetsData'][]; // [SetsData!]!
    SheetsData: NexusGenRootTypes['SheetsData'][]; // [SheetsData!]!
  }
  SetsData: { // field return type
    Day: string | null; // String
    ID: string; // String!
    Key: number; // Int!
    LocationNumber: string | null; // String
    Month: string | null; // String
    school_id: number | null; // Int
    Schools: NexusGenRootTypes['Schools'] | null; // Schools
    SheetsData: NexusGenRootTypes['SheetsData'][]; // [SheetsData!]!
    Title: string | null; // String
    Type: string | null; // String
    Year: string | null; // String
  }
  SheetsData: { // field return type
    Day: string | null; // String
    FilePathDWG: string | null; // String
    FilePathPDF: string | null; // String
    FilePathPNG: string | null; // String
    FilePathTIFF: string | null; // String
    id: number; // Int!
    Month: string | null; // String
    school_id: number | null; // Int
    Schools: NexusGenRootTypes['Schools'] | null; // Schools
    set_id: number | null; // Int
    SetsData: NexusGenRootTypes['SetsData'] | null; // SetsData
    Sheet_Number: string | null; // String
    Title: string | null; // String
    Year: string | null; // String
  }
  User: { // field return type
    confirmed: boolean; // Boolean!
    id: string; // String!
    isAdmin: boolean; // Boolean!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  MiscSheetsData: { // field return type name
    Day: 'String'
    FilePathDWG: 'String'
    FilePathPDF: 'String'
    FilePathPNG: 'String'
    FilePathTIFF: 'String'
    id: 'Int'
    LocationNumber: 'String'
    Month: 'String'
    school_id: 'Int'
    Schools: 'Schools'
    Sheet_Number: 'String'
    Title: 'String'
    Year: 'String'
  }
  Mutation: { // field return type name
    createOneMiscSheetsData: 'MiscSheetsData'
    createOneSchools: 'Schools'
    createOneSetsData: 'SetsData'
    createOneSheetsData: 'SheetsData'
    createSchool: 'Schools'
    deleteOneMiscSheetsData: 'MiscSheetsData'
    deleteOneSchools: 'Schools'
    deleteOneSetsData: 'SetsData'
    deleteOneSheetsData: 'SheetsData'
    deleteOneUser: 'User'
    deleteSchool: 'Schools'
    login: 'User'
    logout: 'User'
    register: 'User'
    updateOneMiscSheetsData: 'MiscSheetsData'
    updateOneSchools: 'Schools'
    updateOneSetsData: 'SetsData'
    updateOneSheetsData: 'SheetsData'
    updateOneUser: 'User'
    updateSchool: 'Schools'
  }
  Query: { // field return type name
    allClusters: 'Schools'
    allSchools: 'Schools'
    allUsers: 'User'
    miscSheetsData: 'MiscSheetsData'
    schools: 'Schools'
    setsData: 'SetsData'
    sheetsData: 'SheetsData'
  }
  Schools: { // field return type name
    Cluster: 'Schools'
    ClusterID: 'String'
    ClusterSchools: 'Schools'
    id: 'Int'
    MiscSheetsData: 'MiscSheetsData'
    SchoolID: 'String'
    SchoolName: 'String'
    SetsData: 'SetsData'
    SheetsData: 'SheetsData'
  }
  SetsData: { // field return type name
    Day: 'String'
    ID: 'String'
    Key: 'Int'
    LocationNumber: 'String'
    Month: 'String'
    school_id: 'Int'
    Schools: 'Schools'
    SheetsData: 'SheetsData'
    Title: 'String'
    Type: 'String'
    Year: 'String'
  }
  SheetsData: { // field return type name
    Day: 'String'
    FilePathDWG: 'String'
    FilePathPDF: 'String'
    FilePathPNG: 'String'
    FilePathTIFF: 'String'
    id: 'Int'
    Month: 'String'
    school_id: 'Int'
    Schools: 'Schools'
    set_id: 'Int'
    SetsData: 'SetsData'
    Sheet_Number: 'String'
    Title: 'String'
    Year: 'String'
  }
  User: { // field return type name
    confirmed: 'Boolean'
    id: 'String'
    isAdmin: 'Boolean'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneMiscSheetsData: { // args
      data: NexusGenInputs['MiscSheetsDataCreateInput']; // MiscSheetsDataCreateInput!
    }
    createOneSchools: { // args
      data: NexusGenInputs['SchoolsCreateInput']; // SchoolsCreateInput!
    }
    createOneSetsData: { // args
      data: NexusGenInputs['SetsDataCreateInput']; // SetsDataCreateInput!
    }
    createOneSheetsData: { // args
      data: NexusGenInputs['SheetsDataCreateInput']; // SheetsDataCreateInput!
    }
    createSchool: { // args
      ClusterID?: string | null; // String
      SchoolId: string; // String!
      SchoolName: string; // String!
    }
    deleteOneMiscSheetsData: { // args
      where: NexusGenInputs['MiscSheetsDataWhereUniqueInput']; // MiscSheetsDataWhereUniqueInput!
    }
    deleteOneSchools: { // args
      where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
    }
    deleteOneSetsData: { // args
      where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
    }
    deleteOneSheetsData: { // args
      where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    deleteSchool: { // args
      SchoolId: string; // String!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    register: { // args
      password: string; // String!
      passwordVerify: string; // String!
      username: string; // String!
    }
    updateOneMiscSheetsData: { // args
      data: NexusGenInputs['MiscSheetsDataUpdateInput']; // MiscSheetsDataUpdateInput!
      where: NexusGenInputs['MiscSheetsDataWhereUniqueInput']; // MiscSheetsDataWhereUniqueInput!
    }
    updateOneSchools: { // args
      data: NexusGenInputs['SchoolsUpdateInput']; // SchoolsUpdateInput!
      where: NexusGenInputs['SchoolsWhereUniqueInput']; // SchoolsWhereUniqueInput!
    }
    updateOneSetsData: { // args
      data: NexusGenInputs['SetsDataUpdateInput']; // SetsDataUpdateInput!
      where: NexusGenInputs['SetsDataWhereUniqueInput']; // SetsDataWhereUniqueInput!
    }
    updateOneSheetsData: { // args
      data: NexusGenInputs['SheetsDataUpdateInput']; // SheetsDataUpdateInput!
      where: NexusGenInputs['SheetsDataWhereUniqueInput']; // SheetsDataWhereUniqueInput!
    }
    updateOneUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    updateSchool: { // args
      ClusterId?: string | null; // String
      NewSchoolId?: string | null; // String
      SchoolId: string; // String!
      SchoolName?: string | null; // String
    }
  }
  Query: {
    miscSheetsData: { // args
      after?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'] | null; // MiscSheetsDataWhereUniqueInput
      before?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'] | null; // MiscSheetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    schools: { // args
      after?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
      before?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    setsData: { // args
      after?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
      before?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    sheetsData: { // args
      after?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      before?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Schools: {
    ClusterSchools: { // args
      after?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
      before?: NexusGenInputs['SchoolsWhereUniqueInput'] | null; // SchoolsWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    MiscSheetsData: { // args
      after?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'] | null; // MiscSheetsDataWhereUniqueInput
      before?: NexusGenInputs['MiscSheetsDataWhereUniqueInput'] | null; // MiscSheetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    SetsData: { // args
      after?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
      before?: NexusGenInputs['SetsDataWhereUniqueInput'] | null; // SetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    SheetsData: { // args
      after?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      before?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  SetsData: {
    SheetsData: { // args
      after?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      before?: NexusGenInputs['SheetsDataWhereUniqueInput'] | null; // SheetsDataWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}