/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */





declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  MiscSheetCreateInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolCreateNestedOneWithoutMiscSheetsInput'] | null; // SchoolCreateNestedOneWithoutMiscSheetsInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  MiscSheetCreateNestedManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['MiscSheetWhereUniqueInput'][] | null; // [MiscSheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MiscSheetCreateOrConnectWithoutSchoolsInput'][] | null; // [MiscSheetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['MiscSheetCreateWithoutSchoolsInput'][] | null; // [MiscSheetCreateWithoutSchoolsInput!]
  }
  MiscSheetCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['MiscSheetCreateWithoutSchoolsInput']; // MiscSheetCreateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
  }
  MiscSheetCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  MiscSheetScalarWhereInput: { // input type
    AND?: NexusGenInputs['MiscSheetScalarWhereInput'][] | null; // [MiscSheetScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathDWG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPDF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPNG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathTIFF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['MiscSheetScalarWhereInput'][] | null; // [MiscSheetScalarWhereInput!]
    OR?: NexusGenInputs['MiscSheetScalarWhereInput'][] | null; // [MiscSheetScalarWhereInput!]
    Sheet_Number?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  MiscSheetUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolUpdateOneWithoutMiscSheetsInput'] | null; // SchoolUpdateOneWithoutMiscSheetsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['MiscSheetUpdateManyMutationInput']; // MiscSheetUpdateManyMutationInput!
    where: NexusGenInputs['MiscSheetScalarWhereInput']; // MiscSheetScalarWhereInput!
  }
  MiscSheetUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['MiscSheetWhereUniqueInput'][] | null; // [MiscSheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MiscSheetCreateOrConnectWithoutSchoolsInput'][] | null; // [MiscSheetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['MiscSheetCreateWithoutSchoolsInput'][] | null; // [MiscSheetCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['MiscSheetWhereUniqueInput'][] | null; // [MiscSheetWhereUniqueInput!]
    deleteMany?: NexusGenInputs['MiscSheetScalarWhereInput'][] | null; // [MiscSheetScalarWhereInput!]
    disconnect?: NexusGenInputs['MiscSheetWhereUniqueInput'][] | null; // [MiscSheetWhereUniqueInput!]
    set?: NexusGenInputs['MiscSheetWhereUniqueInput'][] | null; // [MiscSheetWhereUniqueInput!]
    update?: NexusGenInputs['MiscSheetUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [MiscSheetUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['MiscSheetUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [MiscSheetUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['MiscSheetUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [MiscSheetUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  MiscSheetUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['MiscSheetUpdateWithoutSchoolsInput']; // MiscSheetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
  }
  MiscSheetUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  MiscSheetUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['MiscSheetCreateWithoutSchoolsInput']; // MiscSheetCreateWithoutSchoolsInput!
    update: NexusGenInputs['MiscSheetUpdateWithoutSchoolsInput']; // MiscSheetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
  }
  MiscSheetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  SchoolCreateInput: { // input type
    Cluster?: NexusGenInputs['SchoolCreateNestedOneWithoutClusterSchoolsInput'] | null; // SchoolCreateNestedOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolCreateNestedManyWithoutClusterInput'] | null; // SchoolCreateNestedManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetCreateNestedManyWithoutSchoolsInput'] | null; // MiscSheetCreateNestedManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets?: NexusGenInputs['SetCreateNestedManyWithoutSchoolsInput'] | null; // SetCreateNestedManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSchoolsInput'] | null; // SheetCreateNestedManyWithoutSchoolsInput
  }
  SchoolCreateNestedManyWithoutClusterInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'][] | null; // [SchoolWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutClusterInput'][] | null; // [SchoolCreateOrConnectWithoutClusterInput!]
    create?: NexusGenInputs['SchoolCreateWithoutClusterInput'][] | null; // [SchoolCreateWithoutClusterInput!]
  }
  SchoolCreateNestedOneWithoutClusterSchoolsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutClusterSchoolsInput'] | null; // SchoolCreateOrConnectWithoutClusterSchoolsInput
    create?: NexusGenInputs['SchoolCreateWithoutClusterSchoolsInput'] | null; // SchoolCreateWithoutClusterSchoolsInput
  }
  SchoolCreateNestedOneWithoutMiscSheetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutMiscSheetsInput'] | null; // SchoolCreateOrConnectWithoutMiscSheetsInput
    create?: NexusGenInputs['SchoolCreateWithoutMiscSheetsInput'] | null; // SchoolCreateWithoutMiscSheetsInput
  }
  SchoolCreateNestedOneWithoutSetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutSetsInput'] | null; // SchoolCreateOrConnectWithoutSetsInput
    create?: NexusGenInputs['SchoolCreateWithoutSetsInput'] | null; // SchoolCreateWithoutSetsInput
  }
  SchoolCreateNestedOneWithoutSheetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutSheetsInput'] | null; // SchoolCreateOrConnectWithoutSheetsInput
    create?: NexusGenInputs['SchoolCreateWithoutSheetsInput'] | null; // SchoolCreateWithoutSheetsInput
  }
  SchoolCreateOrConnectWithoutClusterInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutClusterInput']; // SchoolCreateWithoutClusterInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolCreateOrConnectWithoutClusterSchoolsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutClusterSchoolsInput']; // SchoolCreateWithoutClusterSchoolsInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolCreateOrConnectWithoutMiscSheetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutMiscSheetsInput']; // SchoolCreateWithoutMiscSheetsInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolCreateOrConnectWithoutSetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutSetsInput']; // SchoolCreateWithoutSetsInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolCreateOrConnectWithoutSheetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutSheetsInput']; // SchoolCreateWithoutSheetsInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolCreateWithoutClusterInput: { // input type
    ClusterSchools?: NexusGenInputs['SchoolCreateNestedManyWithoutClusterInput'] | null; // SchoolCreateNestedManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetCreateNestedManyWithoutSchoolsInput'] | null; // MiscSheetCreateNestedManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets?: NexusGenInputs['SetCreateNestedManyWithoutSchoolsInput'] | null; // SetCreateNestedManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSchoolsInput'] | null; // SheetCreateNestedManyWithoutSchoolsInput
  }
  SchoolCreateWithoutClusterSchoolsInput: { // input type
    Cluster?: NexusGenInputs['SchoolCreateNestedOneWithoutClusterSchoolsInput'] | null; // SchoolCreateNestedOneWithoutClusterSchoolsInput
    MiscSheets?: NexusGenInputs['MiscSheetCreateNestedManyWithoutSchoolsInput'] | null; // MiscSheetCreateNestedManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets?: NexusGenInputs['SetCreateNestedManyWithoutSchoolsInput'] | null; // SetCreateNestedManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSchoolsInput'] | null; // SheetCreateNestedManyWithoutSchoolsInput
  }
  SchoolCreateWithoutMiscSheetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolCreateNestedOneWithoutClusterSchoolsInput'] | null; // SchoolCreateNestedOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolCreateNestedManyWithoutClusterInput'] | null; // SchoolCreateNestedManyWithoutClusterInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets?: NexusGenInputs['SetCreateNestedManyWithoutSchoolsInput'] | null; // SetCreateNestedManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSchoolsInput'] | null; // SheetCreateNestedManyWithoutSchoolsInput
  }
  SchoolCreateWithoutSetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolCreateNestedOneWithoutClusterSchoolsInput'] | null; // SchoolCreateNestedOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolCreateNestedManyWithoutClusterInput'] | null; // SchoolCreateNestedManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetCreateNestedManyWithoutSchoolsInput'] | null; // MiscSheetCreateNestedManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSchoolsInput'] | null; // SheetCreateNestedManyWithoutSchoolsInput
  }
  SchoolCreateWithoutSheetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolCreateNestedOneWithoutClusterSchoolsInput'] | null; // SchoolCreateNestedOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolCreateNestedManyWithoutClusterInput'] | null; // SchoolCreateNestedManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetCreateNestedManyWithoutSchoolsInput'] | null; // MiscSheetCreateNestedManyWithoutSchoolsInput
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets?: NexusGenInputs['SetCreateNestedManyWithoutSchoolsInput'] | null; // SetCreateNestedManyWithoutSchoolsInput
  }
  SchoolScalarWhereInput: { // input type
    AND?: NexusGenInputs['SchoolScalarWhereInput'][] | null; // [SchoolScalarWhereInput!]
    ClusterID?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['SchoolScalarWhereInput'][] | null; // [SchoolScalarWhereInput!]
    OR?: NexusGenInputs['SchoolScalarWhereInput'][] | null; // [SchoolScalarWhereInput!]
    SchoolID?: NexusGenInputs['StringFilter'] | null; // StringFilter
    SchoolName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  SchoolUpdateInput: { // input type
    Cluster?: NexusGenInputs['SchoolUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolUpdateManyWithoutClusterInput'] | null; // SchoolUpdateManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetUpdateManyWithoutSchoolsInput'] | null; // MiscSheetUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateManyWithoutSchoolsInput'] | null; // SetUpdateManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSchoolsInput'] | null; // SheetUpdateManyWithoutSchoolsInput
  }
  SchoolUpdateManyMutationInput: { // input type
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  SchoolUpdateManyWithWhereWithoutClusterInput: { // input type
    data: NexusGenInputs['SchoolUpdateManyMutationInput']; // SchoolUpdateManyMutationInput!
    where: NexusGenInputs['SchoolScalarWhereInput']; // SchoolScalarWhereInput!
  }
  SchoolUpdateManyWithoutClusterInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'][] | null; // [SchoolWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutClusterInput'][] | null; // [SchoolCreateOrConnectWithoutClusterInput!]
    create?: NexusGenInputs['SchoolCreateWithoutClusterInput'][] | null; // [SchoolCreateWithoutClusterInput!]
    delete?: NexusGenInputs['SchoolWhereUniqueInput'][] | null; // [SchoolWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SchoolScalarWhereInput'][] | null; // [SchoolScalarWhereInput!]
    disconnect?: NexusGenInputs['SchoolWhereUniqueInput'][] | null; // [SchoolWhereUniqueInput!]
    set?: NexusGenInputs['SchoolWhereUniqueInput'][] | null; // [SchoolWhereUniqueInput!]
    update?: NexusGenInputs['SchoolUpdateWithWhereUniqueWithoutClusterInput'][] | null; // [SchoolUpdateWithWhereUniqueWithoutClusterInput!]
    updateMany?: NexusGenInputs['SchoolUpdateManyWithWhereWithoutClusterInput'][] | null; // [SchoolUpdateManyWithWhereWithoutClusterInput!]
    upsert?: NexusGenInputs['SchoolUpsertWithWhereUniqueWithoutClusterInput'][] | null; // [SchoolUpsertWithWhereUniqueWithoutClusterInput!]
  }
  SchoolUpdateOneWithoutClusterSchoolsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutClusterSchoolsInput'] | null; // SchoolCreateOrConnectWithoutClusterSchoolsInput
    create?: NexusGenInputs['SchoolCreateWithoutClusterSchoolsInput'] | null; // SchoolCreateWithoutClusterSchoolsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolUpdateWithoutClusterSchoolsInput'] | null; // SchoolUpdateWithoutClusterSchoolsInput
    upsert?: NexusGenInputs['SchoolUpsertWithoutClusterSchoolsInput'] | null; // SchoolUpsertWithoutClusterSchoolsInput
  }
  SchoolUpdateOneWithoutMiscSheetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutMiscSheetsInput'] | null; // SchoolCreateOrConnectWithoutMiscSheetsInput
    create?: NexusGenInputs['SchoolCreateWithoutMiscSheetsInput'] | null; // SchoolCreateWithoutMiscSheetsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolUpdateWithoutMiscSheetsInput'] | null; // SchoolUpdateWithoutMiscSheetsInput
    upsert?: NexusGenInputs['SchoolUpsertWithoutMiscSheetsInput'] | null; // SchoolUpsertWithoutMiscSheetsInput
  }
  SchoolUpdateOneWithoutSetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutSetsInput'] | null; // SchoolCreateOrConnectWithoutSetsInput
    create?: NexusGenInputs['SchoolCreateWithoutSetsInput'] | null; // SchoolCreateWithoutSetsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolUpdateWithoutSetsInput'] | null; // SchoolUpdateWithoutSetsInput
    upsert?: NexusGenInputs['SchoolUpsertWithoutSetsInput'] | null; // SchoolUpsertWithoutSetsInput
  }
  SchoolUpdateOneWithoutSheetsInput: { // input type
    connect?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SchoolCreateOrConnectWithoutSheetsInput'] | null; // SchoolCreateOrConnectWithoutSheetsInput
    create?: NexusGenInputs['SchoolCreateWithoutSheetsInput'] | null; // SchoolCreateWithoutSheetsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SchoolUpdateWithoutSheetsInput'] | null; // SchoolUpdateWithoutSheetsInput
    upsert?: NexusGenInputs['SchoolUpsertWithoutSheetsInput'] | null; // SchoolUpsertWithoutSheetsInput
  }
  SchoolUpdateWithWhereUniqueWithoutClusterInput: { // input type
    data: NexusGenInputs['SchoolUpdateWithoutClusterInput']; // SchoolUpdateWithoutClusterInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolUpdateWithoutClusterInput: { // input type
    ClusterSchools?: NexusGenInputs['SchoolUpdateManyWithoutClusterInput'] | null; // SchoolUpdateManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetUpdateManyWithoutSchoolsInput'] | null; // MiscSheetUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateManyWithoutSchoolsInput'] | null; // SetUpdateManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSchoolsInput'] | null; // SheetUpdateManyWithoutSchoolsInput
  }
  SchoolUpdateWithoutClusterSchoolsInput: { // input type
    Cluster?: NexusGenInputs['SchoolUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolUpdateOneWithoutClusterSchoolsInput
    MiscSheets?: NexusGenInputs['MiscSheetUpdateManyWithoutSchoolsInput'] | null; // MiscSheetUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateManyWithoutSchoolsInput'] | null; // SetUpdateManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSchoolsInput'] | null; // SheetUpdateManyWithoutSchoolsInput
  }
  SchoolUpdateWithoutMiscSheetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolUpdateManyWithoutClusterInput'] | null; // SchoolUpdateManyWithoutClusterInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateManyWithoutSchoolsInput'] | null; // SetUpdateManyWithoutSchoolsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSchoolsInput'] | null; // SheetUpdateManyWithoutSchoolsInput
  }
  SchoolUpdateWithoutSetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolUpdateManyWithoutClusterInput'] | null; // SchoolUpdateManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetUpdateManyWithoutSchoolsInput'] | null; // MiscSheetUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSchoolsInput'] | null; // SheetUpdateManyWithoutSchoolsInput
  }
  SchoolUpdateWithoutSheetsInput: { // input type
    Cluster?: NexusGenInputs['SchoolUpdateOneWithoutClusterSchoolsInput'] | null; // SchoolUpdateOneWithoutClusterSchoolsInput
    ClusterSchools?: NexusGenInputs['SchoolUpdateManyWithoutClusterInput'] | null; // SchoolUpdateManyWithoutClusterInput
    MiscSheets?: NexusGenInputs['MiscSheetUpdateManyWithoutSchoolsInput'] | null; // MiscSheetUpdateManyWithoutSchoolsInput
    SchoolID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    SchoolName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateManyWithoutSchoolsInput'] | null; // SetUpdateManyWithoutSchoolsInput
  }
  SchoolUpsertWithWhereUniqueWithoutClusterInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutClusterInput']; // SchoolCreateWithoutClusterInput!
    update: NexusGenInputs['SchoolUpdateWithoutClusterInput']; // SchoolUpdateWithoutClusterInput!
    where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
  }
  SchoolUpsertWithoutClusterSchoolsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutClusterSchoolsInput']; // SchoolCreateWithoutClusterSchoolsInput!
    update: NexusGenInputs['SchoolUpdateWithoutClusterSchoolsInput']; // SchoolUpdateWithoutClusterSchoolsInput!
  }
  SchoolUpsertWithoutMiscSheetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutMiscSheetsInput']; // SchoolCreateWithoutMiscSheetsInput!
    update: NexusGenInputs['SchoolUpdateWithoutMiscSheetsInput']; // SchoolUpdateWithoutMiscSheetsInput!
  }
  SchoolUpsertWithoutSetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutSetsInput']; // SchoolCreateWithoutSetsInput!
    update: NexusGenInputs['SchoolUpdateWithoutSetsInput']; // SchoolUpdateWithoutSetsInput!
  }
  SchoolUpsertWithoutSheetsInput: { // input type
    create: NexusGenInputs['SchoolCreateWithoutSheetsInput']; // SchoolCreateWithoutSheetsInput!
    update: NexusGenInputs['SchoolUpdateWithoutSheetsInput']; // SchoolUpdateWithoutSheetsInput!
  }
  SchoolWhereUniqueInput: { // input type
    SchoolID?: string | null; // String
    id?: number | null; // Int
  }
  SetCreateInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolCreateNestedOneWithoutSetsInput'] | null; // SchoolCreateNestedOneWithoutSetsInput
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSetsInput'] | null; // SheetCreateNestedManyWithoutSetsInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetCreateNestedManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SetWhereUniqueInput'][] | null; // [SetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SetCreateOrConnectWithoutSchoolsInput'][] | null; // [SetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SetCreateWithoutSchoolsInput'][] | null; // [SetCreateWithoutSchoolsInput!]
  }
  SetCreateNestedOneWithoutSheetsInput: { // input type
    connect?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SetCreateOrConnectWithoutSheetsInput'] | null; // SetCreateOrConnectWithoutSheetsInput
    create?: NexusGenInputs['SetCreateWithoutSheetsInput'] | null; // SetCreateWithoutSheetsInput
  }
  SetCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SetCreateWithoutSchoolsInput']; // SetCreateWithoutSchoolsInput!
    where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
  }
  SetCreateOrConnectWithoutSheetsInput: { // input type
    create: NexusGenInputs['SetCreateWithoutSheetsInput']; // SetCreateWithoutSheetsInput!
    where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
  }
  SetCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Sheets?: NexusGenInputs['SheetCreateNestedManyWithoutSetsInput'] | null; // SheetCreateNestedManyWithoutSetsInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetCreateWithoutSheetsInput: { // input type
    Day?: string | null; // String
    ID: string; // String!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolCreateNestedOneWithoutSetsInput'] | null; // SchoolCreateNestedOneWithoutSetsInput
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
  }
  SetScalarWhereInput: { // input type
    AND?: NexusGenInputs['SetScalarWhereInput'][] | null; // [SetScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    ID?: NexusGenInputs['StringFilter'] | null; // StringFilter
    Key?: NexusGenInputs['IntFilter'] | null; // IntFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['SetScalarWhereInput'][] | null; // [SetScalarWhereInput!]
    OR?: NexusGenInputs['SetScalarWhereInput'][] | null; // [SetScalarWhereInput!]
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Type?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  SetUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolUpdateOneWithoutSetsInput'] | null; // SchoolUpdateOneWithoutSetsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSetsInput'] | null; // SheetUpdateManyWithoutSetsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SetUpdateManyMutationInput']; // SetUpdateManyMutationInput!
    where: NexusGenInputs['SetScalarWhereInput']; // SetScalarWhereInput!
  }
  SetUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SetWhereUniqueInput'][] | null; // [SetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SetCreateOrConnectWithoutSchoolsInput'][] | null; // [SetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SetCreateWithoutSchoolsInput'][] | null; // [SetCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['SetWhereUniqueInput'][] | null; // [SetWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SetScalarWhereInput'][] | null; // [SetScalarWhereInput!]
    disconnect?: NexusGenInputs['SetWhereUniqueInput'][] | null; // [SetWhereUniqueInput!]
    set?: NexusGenInputs['SetWhereUniqueInput'][] | null; // [SetWhereUniqueInput!]
    update?: NexusGenInputs['SetUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [SetUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['SetUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [SetUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['SetUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [SetUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  SetUpdateOneWithoutSheetsInput: { // input type
    connect?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SetCreateOrConnectWithoutSheetsInput'] | null; // SetCreateOrConnectWithoutSheetsInput
    create?: NexusGenInputs['SetCreateWithoutSheetsInput'] | null; // SetCreateWithoutSheetsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SetUpdateWithoutSheetsInput'] | null; // SetUpdateWithoutSheetsInput
    upsert?: NexusGenInputs['SetUpsertWithoutSheetsInput'] | null; // SetUpsertWithoutSheetsInput
  }
  SetUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SetUpdateWithoutSchoolsInput']; // SetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
  }
  SetUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheets?: NexusGenInputs['SheetUpdateManyWithoutSetsInput'] | null; // SheetUpdateManyWithoutSetsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetUpdateWithoutSheetsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    ID?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolUpdateOneWithoutSetsInput'] | null; // SchoolUpdateOneWithoutSetsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Type?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SetUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SetCreateWithoutSchoolsInput']; // SetCreateWithoutSchoolsInput!
    update: NexusGenInputs['SetUpdateWithoutSchoolsInput']; // SetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
  }
  SetUpsertWithoutSheetsInput: { // input type
    create: NexusGenInputs['SetCreateWithoutSheetsInput']; // SetCreateWithoutSheetsInput!
    update: NexusGenInputs['SetUpdateWithoutSheetsInput']; // SetUpdateWithoutSheetsInput!
  }
  SetWhereUniqueInput: { // input type
    Key?: number | null; // Int
  }
  SheetCreateInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolCreateNestedOneWithoutSheetsInput'] | null; // SchoolCreateNestedOneWithoutSheetsInput
    SetID?: string | null; // String
    Sets?: NexusGenInputs['SetCreateNestedOneWithoutSheetsInput'] | null; // SetCreateNestedOneWithoutSheetsInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetCreateNestedManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetCreateOrConnectWithoutSchoolsInput'][] | null; // [SheetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SheetCreateWithoutSchoolsInput'][] | null; // [SheetCreateWithoutSchoolsInput!]
  }
  SheetCreateNestedManyWithoutSetsInput: { // input type
    connect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetCreateOrConnectWithoutSetsInput'][] | null; // [SheetCreateOrConnectWithoutSetsInput!]
    create?: NexusGenInputs['SheetCreateWithoutSetsInput'][] | null; // [SheetCreateWithoutSetsInput!]
  }
  SheetCreateOrConnectWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SheetCreateWithoutSchoolsInput']; // SheetCreateWithoutSchoolsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetCreateOrConnectWithoutSetsInput: { // input type
    create: NexusGenInputs['SheetCreateWithoutSetsInput']; // SheetCreateWithoutSetsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetCreateWithoutSchoolsInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    SetID?: string | null; // String
    Sets?: NexusGenInputs['SetCreateNestedOneWithoutSheetsInput'] | null; // SetCreateNestedOneWithoutSheetsInput
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetCreateWithoutSetsInput: { // input type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Schools?: NexusGenInputs['SchoolCreateNestedOneWithoutSheetsInput'] | null; // SchoolCreateNestedOneWithoutSheetsInput
    SetID?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
  }
  SheetScalarWhereInput: { // input type
    AND?: NexusGenInputs['SheetScalarWhereInput'][] | null; // [SheetScalarWhereInput!]
    Day?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathDWG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPDF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathPNG?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    FilePathTIFF?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    LocationNumber?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Month?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['SheetScalarWhereInput'][] | null; // [SheetScalarWhereInput!]
    OR?: NexusGenInputs['SheetScalarWhereInput'][] | null; // [SheetScalarWhereInput!]
    SetID?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Sheet_Number?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Year?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    school_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    set_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  SheetUpdateInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolUpdateOneWithoutSheetsInput'] | null; // SchoolUpdateOneWithoutSheetsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateOneWithoutSheetsInput'] | null; // SetUpdateOneWithoutSheetsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetUpdateManyMutationInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetUpdateManyWithWhereWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SheetUpdateManyMutationInput']; // SheetUpdateManyMutationInput!
    where: NexusGenInputs['SheetScalarWhereInput']; // SheetScalarWhereInput!
  }
  SheetUpdateManyWithWhereWithoutSetsInput: { // input type
    data: NexusGenInputs['SheetUpdateManyMutationInput']; // SheetUpdateManyMutationInput!
    where: NexusGenInputs['SheetScalarWhereInput']; // SheetScalarWhereInput!
  }
  SheetUpdateManyWithoutSchoolsInput: { // input type
    connect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetCreateOrConnectWithoutSchoolsInput'][] | null; // [SheetCreateOrConnectWithoutSchoolsInput!]
    create?: NexusGenInputs['SheetCreateWithoutSchoolsInput'][] | null; // [SheetCreateWithoutSchoolsInput!]
    delete?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SheetScalarWhereInput'][] | null; // [SheetScalarWhereInput!]
    disconnect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    set?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    update?: NexusGenInputs['SheetUpdateWithWhereUniqueWithoutSchoolsInput'][] | null; // [SheetUpdateWithWhereUniqueWithoutSchoolsInput!]
    updateMany?: NexusGenInputs['SheetUpdateManyWithWhereWithoutSchoolsInput'][] | null; // [SheetUpdateManyWithWhereWithoutSchoolsInput!]
    upsert?: NexusGenInputs['SheetUpsertWithWhereUniqueWithoutSchoolsInput'][] | null; // [SheetUpsertWithWhereUniqueWithoutSchoolsInput!]
  }
  SheetUpdateManyWithoutSetsInput: { // input type
    connect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['SheetCreateOrConnectWithoutSetsInput'][] | null; // [SheetCreateOrConnectWithoutSetsInput!]
    create?: NexusGenInputs['SheetCreateWithoutSetsInput'][] | null; // [SheetCreateWithoutSetsInput!]
    delete?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SheetScalarWhereInput'][] | null; // [SheetScalarWhereInput!]
    disconnect?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    set?: NexusGenInputs['SheetWhereUniqueInput'][] | null; // [SheetWhereUniqueInput!]
    update?: NexusGenInputs['SheetUpdateWithWhereUniqueWithoutSetsInput'][] | null; // [SheetUpdateWithWhereUniqueWithoutSetsInput!]
    updateMany?: NexusGenInputs['SheetUpdateManyWithWhereWithoutSetsInput'][] | null; // [SheetUpdateManyWithWhereWithoutSetsInput!]
    upsert?: NexusGenInputs['SheetUpsertWithWhereUniqueWithoutSetsInput'][] | null; // [SheetUpsertWithWhereUniqueWithoutSetsInput!]
  }
  SheetUpdateWithWhereUniqueWithoutSchoolsInput: { // input type
    data: NexusGenInputs['SheetUpdateWithoutSchoolsInput']; // SheetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetUpdateWithWhereUniqueWithoutSetsInput: { // input type
    data: NexusGenInputs['SheetUpdateWithoutSetsInput']; // SheetUpdateWithoutSetsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetUpdateWithoutSchoolsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sets?: NexusGenInputs['SetUpdateOneWithoutSheetsInput'] | null; // SetUpdateOneWithoutSheetsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetUpdateWithoutSetsInput: { // input type
    Day?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathDWG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPDF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathPNG?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    FilePathTIFF?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    LocationNumber?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Month?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Schools?: NexusGenInputs['SchoolUpdateOneWithoutSheetsInput'] | null; // SchoolUpdateOneWithoutSheetsInput
    SetID?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Sheet_Number?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Title?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    Year?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  SheetUpsertWithWhereUniqueWithoutSchoolsInput: { // input type
    create: NexusGenInputs['SheetCreateWithoutSchoolsInput']; // SheetCreateWithoutSchoolsInput!
    update: NexusGenInputs['SheetUpdateWithoutSchoolsInput']; // SheetUpdateWithoutSchoolsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetUpsertWithWhereUniqueWithoutSetsInput: { // input type
    create: NexusGenInputs['SheetCreateWithoutSetsInput']; // SheetCreateWithoutSetsInput!
    update: NexusGenInputs['SheetUpdateWithoutSetsInput']; // SheetUpdateWithoutSetsInput!
    where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
  }
  SheetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserUpdateInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    isAdmin?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    username?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // String
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  MiscSheet: { // root type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
    id: number; // Int!
    school_id?: number | null; // Int
  }
  Mutation: {};
  Query: {};
  School: { // root type
    ClusterID?: string | null; // String
    SchoolID: string; // String!
    SchoolName: string; // String!
    id: number; // Int!
  }
  Set: { // root type
    Day?: string | null; // String
    ID: string; // String!
    Key: number; // Int!
    LocationNumber?: string | null; // String
    Month?: string | null; // String
    Title?: string | null; // String
    Type?: string | null; // String
    Year?: string | null; // String
    school_id?: number | null; // Int
  }
  Sheet: { // root type
    Day?: string | null; // String
    FilePathDWG?: string | null; // String
    FilePathPDF?: string | null; // String
    FilePathPNG?: string | null; // String
    FilePathTIFF?: string | null; // String
    Month?: string | null; // String
    Sheet_Number?: string | null; // String
    Title?: string | null; // String
    Year?: string | null; // String
    id: number; // Int!
    school_id?: number | null; // Int
    set_id?: number | null; // Int
  }
  User: { // root type
    id: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  MiscSheet: { // field return type
    Day: string | null; // String
    FilePathDWG: string | null; // String
    FilePathPDF: string | null; // String
    FilePathPNG: string | null; // String
    FilePathTIFF: string | null; // String
    LocationNumber: string | null; // String
    Month: string | null; // String
    Schools: NexusGenRootTypes['School'] | null; // School
    Sheet_Number: string | null; // String
    Title: string | null; // String
    Year: string | null; // String
    id: number; // Int!
    school_id: number | null; // Int
  }
  Mutation: { // field return type
    createOneMiscSheet: NexusGenRootTypes['MiscSheet']; // MiscSheet!
    createOneSchool: NexusGenRootTypes['School']; // School!
    createOneSet: NexusGenRootTypes['Set']; // Set!
    createOneSheet: NexusGenRootTypes['Sheet']; // Sheet!
    deleteOneMiscSheet: NexusGenRootTypes['MiscSheet'] | null; // MiscSheet
    deleteOneSchool: NexusGenRootTypes['School'] | null; // School
    deleteOneSet: NexusGenRootTypes['Set'] | null; // Set
    deleteOneSheet: NexusGenRootTypes['Sheet'] | null; // Sheet
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['User'] | null; // User
    logout: NexusGenRootTypes['User'] | null; // User
    register: NexusGenRootTypes['User'] | null; // User
    updateOneMiscSheet: NexusGenRootTypes['MiscSheet'] | null; // MiscSheet
    updateOneSchool: NexusGenRootTypes['School'] | null; // School
    updateOneSet: NexusGenRootTypes['Set'] | null; // Set
    updateOneSheet: NexusGenRootTypes['Sheet'] | null; // Sheet
    updateOneUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    allClusters: Array<NexusGenRootTypes['School'] | null>; // [School]!
    allSchools: Array<NexusGenRootTypes['School'] | null>; // [School]!
    allUsers: Array<NexusGenRootTypes['User'] | null>; // [User]!
    miscSheet: NexusGenRootTypes['MiscSheet'] | null; // MiscSheet
    miscSheets: NexusGenRootTypes['MiscSheet'][]; // [MiscSheet!]!
    school: NexusGenRootTypes['School'] | null; // School
    schools: NexusGenRootTypes['School'][]; // [School!]!
    set: NexusGenRootTypes['Set'] | null; // Set
    sets: NexusGenRootTypes['Set'][]; // [Set!]!
    sheet: NexusGenRootTypes['Sheet'] | null; // Sheet
    sheets: NexusGenRootTypes['Sheet'][]; // [Sheet!]!
    user: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  School: { // field return type
    Cluster: NexusGenRootTypes['School'] | null; // School
    ClusterID: string | null; // String
    ClusterSchools: NexusGenRootTypes['School'][]; // [School!]!
    MiscSheets: NexusGenRootTypes['MiscSheet'][]; // [MiscSheet!]!
    SchoolID: string; // String!
    SchoolName: string; // String!
    Sets: NexusGenRootTypes['Set'][]; // [Set!]!
    Sheets: NexusGenRootTypes['Sheet'][]; // [Sheet!]!
    id: number; // Int!
  }
  Set: { // field return type
    Day: string | null; // String
    ID: string; // String!
    Key: number; // Int!
    LocationNumber: string | null; // String
    Month: string | null; // String
    Schools: NexusGenRootTypes['School'] | null; // School
    Sheets: NexusGenRootTypes['Sheet'][]; // [Sheet!]!
    Title: string | null; // String
    Type: string | null; // String
    Year: string | null; // String
    school_id: number | null; // Int
  }
  Sheet: { // field return type
    Day: string | null; // String
    FilePathDWG: string | null; // String
    FilePathPDF: string | null; // String
    FilePathPNG: string | null; // String
    FilePathTIFF: string | null; // String
    Month: string | null; // String
    Schools: NexusGenRootTypes['School'] | null; // School
    Sets: NexusGenRootTypes['Set'] | null; // Set
    Sheet_Number: string | null; // String
    Title: string | null; // String
    Year: string | null; // String
    id: number; // Int!
    school_id: number | null; // Int
    set_id: number | null; // Int
  }
  User: { // field return type
    confirmed: boolean; // Boolean!
    id: string; // String!
    isAdmin: boolean; // Boolean!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  MiscSheet: { // field return type name
    Day: 'String'
    FilePathDWG: 'String'
    FilePathPDF: 'String'
    FilePathPNG: 'String'
    FilePathTIFF: 'String'
    LocationNumber: 'String'
    Month: 'String'
    Schools: 'School'
    Sheet_Number: 'String'
    Title: 'String'
    Year: 'String'
    id: 'Int'
    school_id: 'Int'
  }
  Mutation: { // field return type name
    createOneMiscSheet: 'MiscSheet'
    createOneSchool: 'School'
    createOneSet: 'Set'
    createOneSheet: 'Sheet'
    deleteOneMiscSheet: 'MiscSheet'
    deleteOneSchool: 'School'
    deleteOneSet: 'Set'
    deleteOneSheet: 'Sheet'
    deleteOneUser: 'User'
    login: 'User'
    logout: 'User'
    register: 'User'
    updateOneMiscSheet: 'MiscSheet'
    updateOneSchool: 'School'
    updateOneSet: 'Set'
    updateOneSheet: 'Sheet'
    updateOneUser: 'User'
  }
  Query: { // field return type name
    allClusters: 'School'
    allSchools: 'School'
    allUsers: 'User'
    miscSheet: 'MiscSheet'
    miscSheets: 'MiscSheet'
    school: 'School'
    schools: 'School'
    set: 'Set'
    sets: 'Set'
    sheet: 'Sheet'
    sheets: 'Sheet'
    user: 'User'
    users: 'User'
  }
  School: { // field return type name
    Cluster: 'School'
    ClusterID: 'String'
    ClusterSchools: 'School'
    MiscSheets: 'MiscSheet'
    SchoolID: 'String'
    SchoolName: 'String'
    Sets: 'Set'
    Sheets: 'Sheet'
    id: 'Int'
  }
  Set: { // field return type name
    Day: 'String'
    ID: 'String'
    Key: 'Int'
    LocationNumber: 'String'
    Month: 'String'
    Schools: 'School'
    Sheets: 'Sheet'
    Title: 'String'
    Type: 'String'
    Year: 'String'
    school_id: 'Int'
  }
  Sheet: { // field return type name
    Day: 'String'
    FilePathDWG: 'String'
    FilePathPDF: 'String'
    FilePathPNG: 'String'
    FilePathTIFF: 'String'
    Month: 'String'
    Schools: 'School'
    Sets: 'Set'
    Sheet_Number: 'String'
    Title: 'String'
    Year: 'String'
    id: 'Int'
    school_id: 'Int'
    set_id: 'Int'
  }
  User: { // field return type name
    confirmed: 'Boolean'
    id: 'String'
    isAdmin: 'Boolean'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneMiscSheet: { // args
      data: NexusGenInputs['MiscSheetCreateInput']; // MiscSheetCreateInput!
    }
    createOneSchool: { // args
      data: NexusGenInputs['SchoolCreateInput']; // SchoolCreateInput!
    }
    createOneSet: { // args
      data: NexusGenInputs['SetCreateInput']; // SetCreateInput!
    }
    createOneSheet: { // args
      data: NexusGenInputs['SheetCreateInput']; // SheetCreateInput!
    }
    deleteOneMiscSheet: { // args
      where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
    }
    deleteOneSchool: { // args
      where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
    }
    deleteOneSet: { // args
      where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
    }
    deleteOneSheet: { // args
      where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    register: { // args
      password: string; // String!
      passwordVerify: string; // String!
      username: string; // String!
    }
    updateOneMiscSheet: { // args
      data: NexusGenInputs['MiscSheetUpdateInput']; // MiscSheetUpdateInput!
      where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
    }
    updateOneSchool: { // args
      data: NexusGenInputs['SchoolUpdateInput']; // SchoolUpdateInput!
      where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
    }
    updateOneSet: { // args
      data: NexusGenInputs['SetUpdateInput']; // SetUpdateInput!
      where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
    }
    updateOneSheet: { // args
      data: NexusGenInputs['SheetUpdateInput']; // SheetUpdateInput!
      where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
    }
    updateOneUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Query: {
    miscSheet: { // args
      where: NexusGenInputs['MiscSheetWhereUniqueInput']; // MiscSheetWhereUniqueInput!
    }
    miscSheets: { // args
      after?: NexusGenInputs['MiscSheetWhereUniqueInput'] | null; // MiscSheetWhereUniqueInput
      before?: NexusGenInputs['MiscSheetWhereUniqueInput'] | null; // MiscSheetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    school: { // args
      where: NexusGenInputs['SchoolWhereUniqueInput']; // SchoolWhereUniqueInput!
    }
    schools: { // args
      after?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
      before?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    set: { // args
      where: NexusGenInputs['SetWhereUniqueInput']; // SetWhereUniqueInput!
    }
    sets: { // args
      after?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
      before?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    sheet: { // args
      where: NexusGenInputs['SheetWhereUniqueInput']; // SheetWhereUniqueInput!
    }
    sheets: { // args
      after?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      before?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  School: {
    ClusterSchools: { // args
      after?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
      before?: NexusGenInputs['SchoolWhereUniqueInput'] | null; // SchoolWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    MiscSheets: { // args
      after?: NexusGenInputs['MiscSheetWhereUniqueInput'] | null; // MiscSheetWhereUniqueInput
      before?: NexusGenInputs['MiscSheetWhereUniqueInput'] | null; // MiscSheetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    Sets: { // args
      after?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
      before?: NexusGenInputs['SetWhereUniqueInput'] | null; // SetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    Sheets: { // args
      after?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      before?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Set: {
    Sheets: { // args
      after?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      before?: NexusGenInputs['SheetWhereUniqueInput'] | null; // SheetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}